steps              = 200
stride             = 1
number_of_beads    = 40
nbeads             = 10
nchains            = 4
mobility           = 1e-05
qbead              = 0
dir_output         = "/home/jan/Documents/masterthesis/project/results/structure_factor_2"