steps = 100
stride = 50
nbeads = 10
nchains = 8
mobility = 5e-05
rbead = 1.0
qbead = 2.08
force_constant = 100.0
epsilon_LJ = 0.25
sigma_LJ = 2.0
cutoff_LJ = 2.0
lB_debye = 3.077
c_S = 10
cutoff_debye = 4.0
lbox = 20.0
pbc = True
cutoff_pbc = 4.0
save_traj = True
write_traj = True
cwd = '/home/jan/Documents/masterthesis/project/mucus'
fname_traj = '/home/jan/Documents/masterthesis/project/mucus/trajectories/traj_test_time_nbeads_1.gro'
fname_sys = '/home/jan/Documents/masterthesis/project/mucus/configs/cfg_test_time_nbeads_1.toml'
simulation_time = 0.38472414016723633
bonds = None